apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: dev-tooling
  description: lorem ipsum
spec:
  type: team
  memberOf: []
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: sirCheikh
  annotations:
    okta.com/email: cheikh-ahmadou.savadogo@algolia.com
spec:
  memberOf: []